name: Docker CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Image Build
        run: docker build -t ian293382/shorturl-web:latest . 

      - name: Validate Docker Compose
        run: docker compose -f docker-compose.yml config

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: push to dockerhub 
        run: docker push ian293382/shorturl-web:latest
